services:
  
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
    restart: always
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "23309:3306"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ai-server:
    image: ${AI_IMAGE}
    environment:
      - ENV=${ENV}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    restart: always

  backend:
    image: ${BACKEND_IMAGE}            # ghcr.io/<org>/backend:latest 등
    environment:
      SPRING_PROFILES_ACTIVE: dev
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      AES_SECRET_KEY: ${AES_SECRET_KEY}
      FASTAPI_URL: ${FASTAPI_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}           # ghcr.io/<org>/frontend:latest 등
    environment:
      NODE_ENV: production
    ports:
      - "5173:5173"
    restart: always

volumes:
  mysql-data: